# -*- coding: utf-8 -*-
"""Orientation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oX82T9rJJ7QpRHG2igupsPUQlkJLRHWN

Example of addition.
"""

A=2
B=3
C=2+3
print(C)

"""Example of string."""

Greetings = "Advice na, pror"
print(Greetings)

